package com.example.citizenmanagement.models;

public enum FeeMenuOptions {
    TRANG_CHU,
    THEM_KHOAN_THU_PHI,
    DANH_SACH_KHOAN_THU,

    CHI_TIET_KHOAN_THU,
    DANH_SACH_HO_KHAU_CAN_THU_PHI,
    DA_HOAN_THANH_DONG_PHI,
    CHUA_HOAN_THANH_DONG_PHI,
    FEE_PROFILE,
    THEM_KHOAN_THU_DOT,
    THEM_HO_KHAU_DOT,
    DANH_SACH_KHOAN_THU_DOT,
    CHI_TIET_KHOAN_THU_DOT,
    CHUA_HOAN_THANH_PHI_DOT,
    HOAN_THANH_PHI_DOT,
    THONG_TIN_HOA_DON,
    THONG_KE_TONG_HOP,
    THONG_KE_TONG_HOP_UNG_HO

}
